# Generated by Django 4.2.4 on 2023-08-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='region',
        ),
    ]
