# Generated by Django 4.2.4 on 2023-08-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0006_remove_profile_username_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
